name: ChatPlus
version: '${project.version}'
main: com.exemplo.chatplus.ChatPlus
api-version: '26.2'
description: Sistema de chat local, global, staff e cores do texto.
author: donnie1337
softdepend:
  - LoginPlus
  - CargoPlus
  - UtilidadesPlus

commands:
  l:
    description: Envia uma mensagem pelo chat local.
    usage: /l <mensagem>
    permission: chatplus.local
  g:
    description: Envia uma mensagem pelo chat global.
    usage: /g <mensagem>
    permission: chatplus.global
  s:
    description: Envia uma mensagem pelo chat da staff.
    usage: /s <mensagem>
    permission: chatplus.staff
  cor:
    description: Abre o menu para escolher a cor do texto do chat.
    usage: /cor
    permission: chatplus.cor
  chat:
    description: Gerencia o ChatPlus.
    usage: /chat reload
    permission: chatplus.admin

permissions:
  chatplus.local:
    description: Permite enviar mensagens no chat local.
    default: true
  chatplus.global:
    description: Permite enviar mensagens no chat global.
    default: true
  chatplus.staff:
    description: Permite enviar e receber mensagens no chat da staff.
    default: false
  chatplus.admin:
    description: Permite administrar o ChatPlus. Reservada ao Dono via CargoPlus.
    default: false
  chatplus.cor:
    description: Permite escolher a cor das mensagens do chat.
    default: false
